# Site settings
title: NASA/ADS Help Pages
email: adshelp@cfa.harvard.edu
description: All your questions will be answered here.
baseurl: "/help" # the subpath of your site, e.g. /blog/
twitter_username: adsabs
github_username:  adsabs
permalink: /:categories/:title

# Build settings
markdown: kramdown

sass:
    style: :compressed
    sass_dir: _sass
